#ifndef INCLUDE_PARSER_H
#define INCLUDE_PARSER_H

typedef enum token_type_t
{
    TOKEN_IDENTIFIER, TOKEN_ASSIGN, TOKEN_LPAREN, TOKEN_RPAREN, TOKEN_LSPAREN, TOKEN_RSPAREN, TOKEN_COMMA, TOKEN_NUMBER
};

#endif
